FROM python:3

RUN mkdir /app
WORKDIR /app
COPY . ./

RUN pip install -r requirements.txt

# Setup the results folder
RUN mkdir /results
VOLUME /results

# Required for the worker to find the objective module
ENV PYTHONPATH="${PYTHONPATH}:/app/hyperdock/worker"

ENV MONGO_URL="mongo://localhost:27017/hyperdock"

# ENV HYPERDOCK_RESULT_DIR

CMD hyperopt-mongo-worker --poll-interval=0.1 --mongo=${MONGO_URL}
