FROM python:3.6-stretch

RUN mkdir /results
RUN mkdir /data
VOLUME /results
VOLUME /data

RUN mkdir /app
WORKDIR /app
COPY . ./

RUN pip install -e .

ENV HYPERDOCK_IN_DOCKER true

ENTRYPOINT ["hyperdock-worker"]
CMD ["--help"]
